# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3cd2814f6f75692be20518568b4d2cb071f35fb1d998fe799a2c5a9b01e36bfb20fcea7eeb8f429f472d7c873fcd84517a8af2f967ebb74a80d52a7e95cd8771

test:
  secret_key_base: 003b560681c2f792662999f3c1fa8452741aa44d9610e7d6dcb0e41cb04d7a8bc1d19a0b8de2c682d3d80b574893a56496f7a99336bdf17820c239df694f3676

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
